(async function initializePopup() {
  "use strict";

  const core = globalThis.Yt2NotionSubtitleCore;
  const elements = {
    status: document.getElementById("page-status"),
    badge: document.getElementById("package-badge"),
    details: document.getElementById("package-details"),
    file: document.getElementById("package-file"),
    remove: document.getElementById("remove-package"),
    enabled: document.getElementById("enabled"),
    scale: document.getElementById("font-scale"),
    scaleValue: document.getElementById("font-scale-value"),
    offset: document.getElementById("bottom-offset"),
    offsetValue: document.getElementById("bottom-offset-value"),
    message: document.getElementById("message")
  };

  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  const currentVideoId = core.videoIdFromUrl(tab && tab.url ? tab.url : "");
  const stored = await chrome.storage.local.get(["subtitlePackages", "subtitleSettings"]);
  let packages = stored.subtitlePackages || {};
  let settings = { enabled: true, fontScale: 1, bottomOffset: 9, ...(stored.subtitleSettings || {}) };

  function showMessage(text, isError = false) {
    elements.message.textContent = text;
    elements.message.classList.toggle("error", isError);
  }

  function refresh() {
    const pkg = currentVideoId ? packages[currentVideoId] : null;
    elements.status.textContent = currentVideoId
      ? `YouTube video · ${currentVideoId}`
      : "Open a YouTube watch page to import subtitles.";
    elements.file.disabled = !currentVideoId;
    elements.badge.textContent = pkg ? "Ready" : "Not loaded";
    elements.badge.classList.toggle("ready", Boolean(pkg));
    elements.details.textContent = pkg
      ? `${pkg.video.title} · ${pkg.cues.length} cues · ${pkg.target_language}`
      : "Import the JSON generated by subtitle-pack.";
    elements.remove.hidden = !pkg;
    elements.enabled.checked = settings.enabled;
    elements.scale.value = settings.fontScale;
    elements.scaleValue.value = `${Math.round(settings.fontScale * 100)}%`;
    elements.offset.value = settings.bottomOffset;
    elements.offsetValue.value = `${settings.bottomOffset}%`;
  }

  async function saveSettings() {
    await chrome.storage.local.set({ subtitleSettings: settings });
  }

  elements.file.addEventListener("change", async () => {
    const file = elements.file.files && elements.file.files[0];
    if (!file || !currentVideoId) return;
    try {
      const pkg = core.validatePackage(JSON.parse(await file.text()));
      if (pkg.video.id !== currentVideoId) {
        throw new Error(`Package is for ${pkg.video.id}, but this page is ${currentVideoId}.`);
      }
      packages = { ...packages, [currentVideoId]: pkg };
      await chrome.storage.local.set({ subtitlePackages: packages });
      showMessage("Subtitle package imported.");
      refresh();
    } catch (error) {
      showMessage(error.message || "Could not import this file.", true);
    } finally {
      elements.file.value = "";
    }
  });

  elements.remove.addEventListener("click", async () => {
    if (!currentVideoId) return;
    const next = { ...packages };
    delete next[currentVideoId];
    packages = next;
    await chrome.storage.local.set({ subtitlePackages: packages });
    showMessage("Subtitle package removed.");
    refresh();
  });

  elements.enabled.addEventListener("change", async () => {
    settings.enabled = elements.enabled.checked;
    await saveSettings();
  });
  elements.scale.addEventListener("input", async () => {
    settings.fontScale = Number(elements.scale.value);
    elements.scaleValue.value = `${Math.round(settings.fontScale * 100)}%`;
    await saveSettings();
  });
  elements.offset.addEventListener("input", async () => {
    settings.bottomOffset = Number(elements.offset.value);
    elements.offsetValue.value = `${settings.bottomOffset}%`;
    await saveSettings();
  });

  refresh();
})();
